# Generated by Django 5.2.11 on 2026-02-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.IntegerField(choices=[(1, 'Asosiy user'), (2, 'Redaktor'), (3, 'User')], default=1, verbose_name='Foydalanuvchi turi')),
            ],
        ),
    ]
