# Generated by Django 5.2.11 on 2026-02-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountrole",
            name="user_role",
            field=models.IntegerField(
                choices=[(1, "Asosiy user"), (2, "Redaktor"), (3, "Oddiy user")],
                default=1,
                verbose_name="Foydalanuvchi turi",
            ),
        ),
    ]
