# Generated by Django 4.2.10 on 2026-02-10 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_accountrole_user_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccountRole",
        ),
    ]
