# Generated by Django 4.2.10 on 2026-02-10 22:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
