# Generated by Django 4.2.10 on 2026-02-11 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category_name_category_slug"),
        ("posts", "0002_post_dislikes_post_likes_post_slug_post_views_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.category",
            ),
            preserve_default=False,
        ),
    ]
